spring:
  application:
    name: turbine
server:
  port: 8769
security.basic.enabled: false
turbine:
  appConfig: ribbon,feign  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
