eureka:
  client:
    serviceUrl:
      defaultZone: http://docker-cloud-server1:8861/eureka/
spring:
  application:
    name: docker-cloud-client
server:
  port: 8862
management:
  security:
    enabled: false
