eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
server:
  port: 8766
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon
    api-b:
      path: /api-b/**
      serviceId: feign
