server:
  port: 8861
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  application:
    name: docker-cloud-server
management:
  security:
    enabled: false
